### ISSUE TITLE
Two containers in same Pod without name should throw error

### ISSUE THREAD

**Issue by kadel** [surajssd/kapp#32]
```yaml
name: test

containers:
- image: quay.io/tomkral/nonroot-nginx
- image: quay.io/tomkral/sleeper
```

the result is invalid:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
      name: test
    spec:
      containers:
      - image: quay.io/tomkral/nonroot-nginx
        name: ""
        resources: {}
      - image: quay.io/tomkral/sleeper
        name: ""
        resources: {}
status: {}
```

I expected this to throw error saying that if there are multiple containers they have to have unique names
