### ISSUE TITLE
Top level name is not propagated to single service

### ISSUE THREAD

**Issue by kadel** [surajssd/kapp#33]
```yaml
name: test

containers:
 - image: quay.io/tomkral/nonroot-nginx

services:
  - ports:
    - port: 8080
```

the result is invalid service:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    app: test
status:
  loadBalancer: {}
```

what I expected is Service named 'test'
