### ISSUE TITLE
volume entry in PodSpec is generated every time volume is used

### ISSUE THREAD

**Issue by kadel** [surajssd/kapp#34]
```yaml
name: test

containers:
- image: quay.io/tomkral/nonroot-nginx
  name: nginx
  volumeMounts:
    - mountPath: /var/lib/nginx
      name: test
- image: quay.io/tomkral/sleeper
  name: data
  volumeMounts:
    - mountPath: /data
      name: test

services:
  - name: test
    type: LoadBalancer
    ports:
      - port: 8080

persistentVolumes:
  - name: test
    size: 500Mi
```

outputs invalid deployment:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
      name: test
    spec:
      containers:
      - image: quay.io/tomkral/nonroot-nginx
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/nginx
          name: test
      - image: quay.io/tomkral/sleeper
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: test
      volumes:
      - name: test
        persistentVolumeClaim:
          claimName: test
      - name: test
        persistentVolumeClaim:
          claimName: test
status: {}
```

There should be only one entry for each PVC.
