### ISSUE TITLE
Autogenerating port names

### ISSUE THREAD

**Issue by kadel** [surajssd/kapp#38]
if multiple ports are specified in a single service they have to be named. see https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services

We can make names optional and autogenerate them if no name is specified.

```yaml
name: test

containers:
- name: nginx
  image: quay.io/tomkral/nonroot-nginx
- name: nginx2
  image: nginx

services:
  - name: test
    type: LoadBalancer
    ports:
      - port: 8080
        # default name: port-8080
      - ports: 80
        # default name: port-80

```
