### ISSUE TITLE
Wrong port number when multiple ports specified 

### ISSUE THREAD

**Issue by kadel** [surajssd/kapp#39]
```yaml
name: test

containers:
- name: nginx
  image: quay.io/tomkral/nonroot-nginx
- name: nginx2
  image: nginx

services:
  - name: test
    type: LoadBalancer
    ports:
      - port: 8080
        name: port-8080
      - ports: 80
        name: port-80
```

creates service with a wrong port number for the second port

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  ports:
  - name: port-8080
    port: 8080
    targetPort: 0
  - name: port-80
    port: 0
    targetPort: 0
  selector:
    app: test
  type: LoadBalancer
status:
  loadBalancer: {}

```

it should look like this:
```yaml
  ports:
  - name: port-8080
    port: 8080
    targetPort: 0
  - name: port-80
    port: 80
    targetPort: 0
```
